### ISSUE TITLE
Logger initialization issue

### ISSUE THREAD

**Issue by yunyu** [stevenleeg/geemusic#111]
```
22:57:46 web.1  | Exception in thread Thread-3:
22:57:46 web.1  | Traceback (most recent call last):
22:57:46 web.1  |   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
22:57:46 web.1  |     self.run()
22:57:46 web.1  |   File "/usr/lib/python3.4/threading.py", line 868, in run
22:57:46 web.1  |     self._target(*self._args, **self._kwargs)
22:57:46 web.1  |   File "/home/appserver/geemusic/geemusic/utils/music.py", line 51, in index_library
22:57:46 web.1  |     self.logger.debug('Fetching library...')
22:57:46 web.1  | AttributeError: 'NoneType' object has no attribute 'debug'
```

The weird part is that I do get log messages (DISCOVERED, etc), but all the requests fail after the first few messages.

**Comment by yunyu** [comment]
If I replace those with print statements, I get:

```
23:10:46 web.1  |   File "/home/appserver/geemusic/.venv/lib/python3.4/site-packages/flask_ask/models.py", line 254, in _output_speech
23:10:46 web.1  |     xmldoc = ElementTree.fromstring(speech)
23:10:46 web.1  |   File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
23:10:46 web.1  |     parser.feed(text)
23:10:46 web.1  | TypeError: 'bool' does not support the buffer interface
```

I am running Python 3.4.

**Comment by yunyu** [comment]
It seems to work after upgrading to 3.6 via pyenv, but there's still a bunch of other misc issues. Closing.

**Comment by yunyu** [comment]
Just kidding, the same happens after a while with 3.6.

**Comment by charlesinwald** [comment]
I also have this issue.

**Comment by stevenleeg** [comment]
This hasn't seen any recent activity and will therefore be closed. Feel free to comment or file a new issue if you're still having trouble.
